# Generated by Django 4.0.2 on 2022-03-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_user_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.IntegerField()),
                ('password', models.CharField(max_length=256)),
                ('about', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='mobile_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
