# Generated by Django 4.0.2 on 2022-03-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_doctor_registeration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(default='hk', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mobile_number',
            field=models.BigIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='language',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registeration_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
