# Generated by Django 4.0.2 on 2022-03-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_task_alter_doctor_email_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(choices=[('DW', 'Draw'), ('AS', 'Assessment')], default='OH', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.user'),
            preserve_default=False,
        ),
    ]
