# Generated by Django 4.0.2 on 2022-03-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_task_doctor_id_task_task_task_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
        migrations.AddField(
            model_name='task',
            name='user_email',
            field=models.ForeignKey(db_column='email', default='abc', on_delete=django.db.models.deletion.CASCADE, to='product.user', to_field='email'),
            preserve_default=False,
        ),
    ]
