# Generated by Django 4.0.2 on 2022-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_rename_answers_answer_rename_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
