# Generated by Django 4.0.2 on 2022-03-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(choices=[('DW', 'Draw'), ('IM', 'Image')], default='OH', max_length=2),
        ),
    ]
