# Generated by Django 4.0.3 on 2022-03-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
