# Generated by Django 4.0.3 on 2022-03-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_task_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_image', models.TextField(blank=True, null=True)),
                ('submitted_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('task_type', models.CharField(max_length=25)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.doctor')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.user')),
            ],
        ),
    ]
