# Generated by Django 4.0.3 on 2022-03-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_task_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
