# Generated by Django 4.0.3 on 2022-03-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_task_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedtask',
            name='doctor_comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submittedtask',
            name='task_score',
            field=models.IntegerField(null=True),
        ),
    ]
