# Generated by Django 4.0.3 on 2022-03-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_submittedtask_doctor_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedtask',
            name='task_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
