# Generated by Django 4.0.2 on 2022-04-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_doctor_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_between',
            field=models.CharField(default='09:00 AM - 1.00 PM', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='MA In Counseling Psychology', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='Stress, Anxiety, Relationship Issues, Body Image, Self Confidence, Anger', max_length=256),
            preserve_default=False,
        ),
    ]
