# Generated by Django 4.0.2 on 2022-04-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_doctor_available_between_doctor_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_between',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
