# Generated by Django 4.0.2 on 2022-04-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_doctor_available_between'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='about',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
