# Generated by Django 4.0.2 on 2022-04-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_alter_doctor_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
