# Generated by Django 3.1.2 on 2022-05-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20220517_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
    ]
