# Generated by Django 3.1.2 on 2022-05-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_remove_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='submittedtask',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='submittedtask',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='submittedtask',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_email',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='GameScore',
        ),
        migrations.DeleteModel(
            name='SubmittedTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
